协作工具: {
  shape: class

  CRM: "客户关系"
  文件同步: "云盘"
  电子邮件
  OFFICE: "办公套件"
  项目管理
  任务管理
  虚拟白板
  聊天工具
}

个人工具: {
  shape: class

  CRM: "客户关系"
  密码管理
  笔记
  文件同步: "云盘"
  IDE: "编辑器"
  设计工具
  电子邮件
  时间追踪
}

企业工具: {
  shape: class

  进销存
  订单管理
}
