@startmindmap 悟空
* 悟空
	* 孙悟空，猴子如果学会悟空
		*_ 变成美猴王
		*_ 七十二变
		*_ 腾云驾雾
		*_ 大闹天宫
		*_ 立地成佛
	* 空
		*_ 《摩诃般若波罗蜜多心经》
		*_ 无相《金刚经》
		*_ 无相是空的表现，一体两面
		*_ 无名《道德经》
		*_ 名相《楞伽léng qié经》
		*_ 器《易经·系辞》
		*_ 不器《论语·为政篇》子曰：“君子不器。”
	* 乌鸦是种什么样的鸟
		*_ 大多数数的哺乳动物是色盲
			*_ 夜行，需要夜视、嗅觉、听觉
			*_ 低头食草，听觉灵敏
		*_ 灵长类动物杂食吃水果、蘑菇
			*_ 不能分辨颜色都饿死、毒死
		*_ 昆虫能识别紫外线，不能识别红色
		*_ 鸟类可以识别紫外线，眼球具有双重调节
			*_ 可以望远
			*_ 也可以看近
		*_ 鸟类没有耳廓，喜欢高亢尖锐的声音
		*_ 乌鸦是五彩斑斓的黑，叫声优美
		*_ 鸟中的帅哥靓妹
		*_ 我们对乌鸦的定义都是错误的
	* 水杯
		*_ 形状，单侧观察，方形还是圆形
		*_ 世界是三维的，视觉是二维的，大脑进行了渲染
		*_ 颜色、形状、味道、触觉都是大脑的渲染
		*_ 本质：杯子!=帽子，杯子!=手机支架,执着
	* 标签
		*_ 人、事、物打标签
		*_ 优点
			*_ 降低消耗
			*_ 快速反应
			*_ 可遗传，无需学习
			*_ 表观基因
		*_ 缺点
			*_ 刻板印象
			*_ 以偏带全
			*_ 缺少创新
			*_ 不思考
		*_ 毛骨悚然的危害
			*_ 隐藏在潜意识里，甚至基因里
			*_ 影响我们方方面面
			*_ 不停的伤害我们而我们全然不知
		*_ 情绪
			*_ 路怒症,法律缺失的必然补充
			*_ 你瞅啥
			*_ 荣誉谋杀(每年大约有5000名妇女死于这种谋杀形式)
			*_ 职场
			*_ 部落效应、联想阶梯
			*_ 家庭
		*_ 更可悲的饮食习惯
			*_ 盐,北方内陆缺盐
			*_ 糖,水果无法储藏
			*_ 脂,寒冬和饥荒，谷氨酸钠
			*_ 生活习惯是由成千上万年前祖先的影响
			*_ 我们根本没有自主能力，不过室基因的奴隶而已
	* 如何悟
		*_ 遇到负面情绪就去看他、关照他、思考他为什么而来，不用抵触，不用意志力
		*_ 外在的、内在的噪音，观世音、观自在
		*_ 别名：正念、禅定
		* 科学依据大脑的结构
			*_ 脑核：日常基本活动，包括呼吸、心跳、觉醒、运动、睡眠、平衡等
			*_ 杏仁核: 进化比较古老的部分蜥蜴脑，掌管打或者逃，左右情绪
			*_ 大脑皮层则负责人脑较高级的认知和情绪功能,听说读写，记忆联想
			*_ 杏仁核具有抑制大脑皮层的能力，愤怒的时候出现张口结舌、哑口无言
			*_ 杏仁核一之在说，能动手就别哔哔
			* 类比
				*_ 脑核、杏仁核这类原始脑就是系统软件，出厂就设置好了，不可更改
				*_ 大脑皮层是应用软件，使用过程中安装调试好的，优先级低于系统软件
				*_ 开车、游泳、滑雪等技能都是应用软件
				*_ 系统1和系统2
		* 流程
			*_ 接受任何信息
			*_ 系统软件会先接手，加工、渲染，加滤镜，删除无用信息后转交给应用软件
			*_ 降低应用软件能量消耗，争取全自动无人驾驶
			*_ 负面情绪出现
			*_ 系统软件优先启动杏仁核
			*_ 抢占了CPU资源，开始准备反击，加强对方攻击性加强，给对方加怪物模板，寻找对方弱点，忽视一切事实
			*_ 不由自主的转意目标，将责任归咎他人，甚至是无理取闹，有时甚至扭曲错误指向了自己
			*_ 一旦观注负面情绪，开始思考
			*_ 理性脑，自然上线，主动启动相关应用程序，渡让部分控制权
			*_ 平息情绪，去除掉滤镜，重新审视事实，快速的进入平和自然的状态
@endmindmap
