@startmindmap 服务
* 服务
** 价值
*** <&star>产生收益
****_ 提高质量
****_ 扩大市场
****_ 樊登
****_ 付费排名
****_ 聚划算
*** 减少支出
****_ 提高效率
****_ 节约成本
****_ 打单软件
*** 消费
****_ 淘宝
****_ 外卖
****_ 打车
*** 娱乐
****_ 吃鸡
****_ 王者荣耀
** 自带宣传属性
*** 直播带货
****_ 口红
****_ 美妆
*** 社交网络
****_ facebook
****_ 微博
****_ 抖音
***_ 哨子
***_ 快递包装
***_ <&star>假眉毛
** 收费
***_ 周期性消费
***_ 重复消费
** 持续激励
***_ 频繁正反馈
***_ 赞
***_ 评论
** 小而专
***_ 细分领域最强
***_ 竞争不激烈
***_ 独创性
@endmindmap
